site_name: bmyjacks 知识库
site_url: https://bmyjacks.net
site_description: 分享个人的知识和经验
site_author: bmyjacks
repo_url: https://github.com/bmyjacks/bmyjacks.net
repo_name: bmyjacks/bmyjacks.net

copyright: Copyright &copy; 2020 - 2025 bmyjacks. <p xmlns:cc="http://creativecommons.org/ns#" ><a href="http://creativecommons.org/licenses/by/4.0/" target="_blank" rel="license noopener noreferrer" style="display:inline-block;"><img style="height:31px!important;margin-left:3px;vertical-align:text-bottom;" src="https://assets.bmyjacks.net/img/by.svg"></a></p>

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  language: zh
  font: false
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.prune
    - toc.follow
    - navigation.top
    - search.suggest
    - search.share
    - content.tabs.link
    - content.code.copy
    - content.code.annotate

extra_css:
  - stylesheets/fonts.css

plugins:
  - search
  - social:
      enabled: !ENV [CI, false]
      cards_layout_options:
        font_family: Noto Sans SC
  - glightbox
  - minify:
      minify_html: true
      minify_js: false
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.blocks.caption
  - footnotes
  - tables
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
      auto_title: true
      linenums_style: pymdownx-inline
      line_spans: __span
  - pymdownx.snippets
  - admonition
  - pymdownx.details

nav:
  - 主页: index.md
  - Markdown:
      - 启程: markdown/index.md
      - 基本用法: markdown/basic.md
  - Homelab:
      - 介绍: homelab/index.md
      - 硬件:
          - 选择服务器: homelab/choose-server.md
          - 选择 CPU: homelab/choose-cpu.md
          - 选择硬 RAID 卡: homelab/choose-hardware-raid.md
          - 选择软件 RAID 方案: homelab/choose-software-raid.md
      - 软件:
          - Arch Linux: os/archlinux.md
          - NixOS: os/nixos.md
          - 安装 iSM: homelab/install-ism.md
