[project]
name = "bmyjacks-net"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-glightbox>=0.4.0",
 "mkdocs-material[imaging]>=9.6.15",
 "mkdocs-minify-plugin>=0.8.0",
]
